export 'login/login_screen.dart';
export 'home/home.dart';
export 'nav/nav.dart';
export 'profile/profile_screen.dart';
export 'explore/explore.dart';
export 'splash/splash_screen.dart';
export 'src/my_app.dart';
export 'questionnaire/questionnairescr.dart';
export 'analysis/analysis.dart';